# Generated by Django 5.1.6 on 2025-02-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='python', max_length=255),
            preserve_default=False,
        ),
    ]
