# Generated by Django 5.1.6 on 2025-02-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('doubt', 'Doubt/Question'), ('learning', 'Learning'), ('resource', 'Resource')], default='learning', max_length=20),
        ),
    ]
