# Generated by Django 5.1.6 on 2025-02-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='topic',
        ),
    ]
